version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

#python:
#  install:
#    - requirements: docs/requirements.txt

mkdocs:
  configuration: docs/mkdocs.yml
  fail_on_warning: false

submodules:
  exclude: all