mongo:
  server: "localhost:27017"
  #  server: "falcon.nims.go.jp:27017"
  db: "supercon_tmp"
  #  db: "supercon_dev_4"
  #  db: "supercon_sample"

root-path: '/'

label-studio:
  url: "http://falcon.nims.go.jp/label-studio"
  project_id: "1"
