mongo:
#  server: "localhost:27017"
  server: "falcon.nims.go.jp:27017"
  db: "supercon_correction"
  #  db: "supercon_dev_4"
#  db: "supercon_develop"

root-path: '/'

label-studio:
  url: "http://falcon.nims.go.jp/label-studio"
  project_id: "1"
