site_name: SuperCon 2 Documentation
repo_url: https://github.com/lfoppiano/supercon2
repo_name: GitHub
site_description: Guidelines for SuperCon 2 curation for SuperCon database
docs_dir: .
plugins:
  - search
theme:
  name: readthedocs
nav:
  - Home: 'guideline/guidelines.md'